### ISSUE TITLE
change routing between pages from angular router-extensions to native-script routing mechanics

### ISSUE THREAD

**Issue by pat-St** [stefan0612/HTWGapp#17]
from RouterExtensions to NativeScriptRouterModule

**Comment by pat-St** [comment]
ref: https://docs.nativescript.org/core-concepts/angular-navigation#router-link

**Comment by stefan0612** [comment]
RoutingExtensions and the RouterModule are a pair and go hand in hand. After using the routerExtensions the Angular routing module loads the specified component for the route. Because of the fact, that the Routermodule is already implemented this won't be worked on
